### ISSUE TITLE
GRAFANA_TOKEN env variable is not passed correctly

### ISSUE THREAD

**Issue by jl2397** [grafana-toolbox/grafana-import#16]
When the Grafana class is initialized in grafana.py, there is only a check for the "url" field in the parameters. If the GRAFANA_TOKEN env variable is set, the token is never passed to the GrafanaApi client and therefore results in a GrafanaUnauthorizedError when making requests using grafana_client. A credential field needs to be added to the `from_url` call to populate the GRAFANA_TOKEN env variable.

**Comment by amotl** [comment]
Dear @julialau23. Thanks a stack for the report. May we ask if you would have the capacities to submit a patch?

**Comment by julialau23** [comment]
Hi Andreas,

Sure I can do that. Can I get write access to the repo?

**Comment by amotl** [comment]
Hi @julialau23. We just wanted to check if you have been able to come up with a solution for this?

**Comment by julialau23** [comment]
Hi @amotl, apologies for the delay. Pull request has been opened.

**Comment by amotl** [comment]
Thanks a stack for your contribution per GH-19. I've just merged the improvement with GH-20.

**Comment by amotl** [comment]
Your improvements have been released per grafana-import v0.3.0, now on PyPI.

**Comment by amotl** [comment]
I think it will be safe to close this issue. Please re-open otherwise.
