### ISSUE TITLE
feat: Add option to import all dashboards from a directory

### ISSUE THREAD

**Issue by vrymar** [grafana-toolbox/grafana-import#25]
Need to add a feature to import all dashboards available in a provided directory.

**Comment by amotl** [comment]
Hi. [grafana-import v0.4.0](https://github.com/grafana-toolbox/grafana-import/releases/tag/v0.4.0) is [on PyPI now](https://pypi.org/project/grafana-import/). It includes your improvement GH-27, thanks again.
