### ISSUE TITLE
Maintenance and Features

### ISSUE THREAD

**Issue by amotl** [grafana-toolbox/grafana-import#3]
Dear Jean-Francois,

we are aiming to level up with [grafanalib-upload-dashboard.py] of [grafana-client](https://github.com/panodata/grafana-client), and plan to provide users with a better command-line program interface to upload JSON artefacts from files to the Grafana API, most prominently, dashboards.

We think you already did an excellent job on behalf of this grafana-import package, so we would like to contribute something to support you on this journey. We may look into a few issues, cut some edges, and send a few maintenance patches, and we hope they will be received well.

Please also let us know if you have any specific areas in mind where we could support you and this project. Thanks!

With kind regards,
Andreas.

[grafanalib-upload-dashboard.py]: https://github.com/panodata/grafana-client/blob/main/examples/grafanalib-upload-dashboard.py

**Comment by peekjef72** [comment]
Hi Andreas,

Great news! 
This tool was born in my company because teams had their own graphana/prometheus sandboxes to build metrics and dashboards and then wanted to share the results in the main centralized stack.
Nowaday, they have changes their mind and play with others rendering tools.
As a consequence I do not have any use case to play with... 
I believe that tool like that belongs to its users so it is time to share.
I don't know exactly how it could be achived but Github surely allows to add you as a repo maintainer.

JFPIK-

**Comment by peekjef72** [comment]
Andreas
Please could you reach me by email on jfpik78@gmail.com ?
I have sent you an email to andreas.motl@elmyra.de, the address I found on your github profile, but I not sure you can have received it.

**Comment by amotl** [comment]
Hi. I currently do not receive on this email address, apologies. If you are open to contribute the repository to our humble place at panodata, just add me as a contributor (owner), so I can transfer it to the organization.

As I've also invited you there, you can still be in charge, like before. Effectively, nothing changes but the URL (GitHub will employ corresponding redirects), but maintenance can be done by more people than before, collaboratively. Thank you!

**Comment by amotl** [comment]
It looks like we are doing a very bad job maintaining our self-hosted email servers well enough. Currently, it looks like we have been disconnected from Gmail completely. Apologies.

```
[<jfpik78@gmail.com>](mailto:jfpik78@gmail.com): host gmail-smtp-in.l.google.com[74.125.133.27] said:
    550-5.7.26 This mail has been blocked because the sender is
    unauthenticated. 550-5.7.26 Gmail requires all senders to authenticate with
    either SPF or DKIM. 550-5.7.26  550-5.7.26  Authentication results:
    550-5.7.26  DKIM = did not pass 550-5.7.26  SPF [e-habit.at] with ip:
    [195.201.14.7] = did not pass 550-5.7.26  550-5.7.26  For instructions on
    setting up authentication, go to 550 5.7.26
    https://support.google.com/mail/answer/81126#authentication
    y6-20020adff6c6000000b0034abe4e2db0si410528wrp.935 - gsmtp (in reply to end
    of DATA command)
```

/cc @einsiedlerkrebs

**Comment by amotl** [comment]
We just configured SPF on the domain, but that might not be sufficient to improve the situation.

> Starting in 2024, email senders must meet the requirements described here to send email to Gmail personal accounts.
>
> -- https://support.google.com/a/answer/81126
> -- https://support.google.com/a/answer/2466563

**Comment by amotl** [comment]
Hi again. Turns out, adding a DMARC record is not too difficult.

> #### DMARC alignment options
>
> DMARC passes or fails a message based on how closely the message From: header matches the sending domain specified by either SPF or DKIM.
>
> -- [Define your DMARC record](https://support.google.com/a/answer/10032169)

Now that https://mxtoolbox.com/emailhealth/e-habit.at/ signals success, I was able to get mail through to you.

**Comment by amotl** [comment]
While [grafana-tools](https://github.com/grafana-tools) is already taken, we could also use one of [grafana-contrib](https://github.com/grafana-contrib), [grafana-toolbox](https://github.com/grafana-toolbox), or [grafana-utilities](https://github.com/grafana-utilities) as a representation for a corresponding collective. wdyt?

**Comment by amotl** [comment]
The repository has been migrated to the [Grafana Toolbox](https://github.com/grafana-toolbox) organization on GitHub. Thanks, @peekjef72!

-- https://github.com/grafana-toolbox/grafana-import

Now, the next items to work on, are, roughly:

- GH-7

Closing this.
