### ISSUE TITLE
Software tests and CI. Ad hoc operation mode. "Builder" and "live reload" features.

### ISSUE THREAD

**Issue by amotl** [grafana-toolbox/grafana-import#7]
## About

Coming from GH-3, we would like to add a few more items to this project.

### Software Tests
I think the application dearly needs software tests. Otherwise, we can't easily bring in any further changes.

- Add basic software tests to verify the program roughly works, has no typos, and got its dependency definitions right.
- By adding a CI configuration, dependency updates can be conveniently driven by GitHub's Dependabot.

### Features
On the page of actual features, we would like to add:

- An operation mode to invoke `grafana-import` ad hoc, without needing a configuration file at all. 
- Because people are using builders to generate dashboard representations in JSON format, like [Grafonnet](https://github.com/grafana/grafonnet/), [grafanalib](https://github.com/weaveworks/grafanalib), [grafana-dashboard](https://github.com/fzyzcjy/grafana_dashboard_python), or [cog](https://github.com/grafana/cog), it will be nice if the program offers corresponding support to not only upload JSON, but also have the legroom to invoke the builder first, and consume its output before uploading.
- A "live reloading" functionality will automatically (re-)upload a dashboard to Grafana when its JSON representation has been changed on disk.

**Comment by amotl** [comment]
Hi again,

those patches implement the proposals outlined above. We hope they will be received well. We've used the new features on  a few occasions already, and we really love them, making Grafana Dashboard authoring a breeze.

- GH-8
- GH-9
- GH-10
- GH-12
- GH-13

We are confident the behaviour does not significantly change for existing users compared to release 0.2.0, but of course, we want to make sure that a new release would be maximally compatible with the previous one, in order not to cause any downstream havocs.

Which procedure would you favor for that, @peekjef72?

- Just release 0.3.0 to PyPI, and if something breaks on your or other ends, the designated advice is to report it to the issue tracker, and downgrade by using `pip install grafana-import==0.2.0`, to re-gain compatibility without further ado.
- Run a testing release using version 0.3.0dev1, to give people a chance to evaluate the new release before having a GA release.

**Comment by peekjef72** [comment]
> We are confident the behaviour does not significantly change for existing users compared to release 0.2.0, but of course, we want to make sure that a new release would be maximally compatible with the previous one, in order not to cause any downstream havocs.
> 
> Which procedure would you favor for that, @peekjef72?
> 
> * Just release 0.3.0 to PyPI, and if something breaks on your or other ends, the designated advice is to report it to the issue tracker, and downgrade by using `pip install grafana-import==0.2.0`, to re-gain compatibility without further ado.
> * Run a testing release using version 0.3.0dev1, to give people a chance to evaluate the new release before having a GA release.

Hi Andreas,
I think we can use the first  procedure.
Tell me when the release of 0.3.0 is ready. For security constraints in my company, I can't access to github repos directly (can git clone). So it is more confortable for me to work on this at week-end...

**Comment by amotl** [comment]
Thank you very much.

> I can't access GitHub repos directly very well during the week.

Maybe you can also add me as a member on the PyPI project, so I can quicky run bugfix releases if something goes south? I am also `amotl` there.

**Comment by peekjef72** [comment]
Hi.
I invite you on pipy for grafana-import and grafana-snapshot to become
maintainer.
I will transfer grafana-snapshot to grafana-toolbox repos surely today :
I'm currently working on a branch 0.3.0 that is functioning on grafana v
10.x ! still in synchronizing work done at job (without github access) and
home repos :there should be a better method but not found yet...

JFPIK-

Le ven. 26 avr. 2024, 23:19, Andreas Motl ***@***.***> a
écrit :

**Comment by amotl** [comment]
Hi JFPIK,

please take your time, and thanks a stack!

> I'm currently working on a branch 0.3.0 for grafana-snapshot that is functioning on grafana v10.x. Still in synchronizing work done at job (without github access) and home repos :there should be a better method but not found yet...

Good luck!

Cheers,
Andreas.

**Comment by amotl** [comment]
In other news, I started to present the modernizations of `grafana-import` to the Grafana Community as a preview, after merging the recent feature PRs.

https://community.grafana.com/t/backing-up-or-committing-dashboards-to-github/26194/9

Are you also a member of the Grafana Community Forum, so I can reference your handle more appropriately instead of linking to GitHub?

**Comment by peekjef72** [comment]
> Are you also a member of the Grafana Community Forum, so I can reference
your handle more appropriately instead of linking to GitHub?
 no I didn't have one : I just created an access with my github account so
peekjef72 is now "existing".
anyway the article you already wrote is fine (and far enough) thanks !

Le sam. 27 avr. 2024 à 12:44, Andreas Motl ***@***.***> a
écrit :

**Comment by amotl** [comment]
Hi again. I think it will be safe to close this ticket. It looks like all enumerated items and discussions have been handled well. Thank you so much for your support, @peekjef72. If you think anything has not been addressed well, please re-open.
